### ISSUE TITLE
An inconsistency between docs and the code

### ISSUE THREAD

**Issue by trejder** [schmunk42/database-command#17]
There's an inconsistency between what you write in docs ([README.md](https://github.com/schmunk42/database-command/blob/master/README.md)) and what you actually have in latest version of your code (tested on version [0.8.12](https://github.com/schmunk42/database-command/tags) released on 11 Apr 2014):

1. Docs says about `yiic database` command, while it actually is `yiic edatabase` due to naming scheme you used in your code. One must rename `EDatabaseCommand` class to `DatabaseCommand` to fix this or use `yiic edatabase` command instead.

2. Running command without any parameters (i.e. `yiic edatabase`) does display help, but also throws `Error: Unknown action: index` error. You may want to mute that somehow.

For people, who are using yiic commands for the first time, it would be a great addition to extend installation part of your doc as well. Two-line paragraph mentioning, that contents of zip file should be placed in `protected/commands` (which must be created, if does not exist) and that it must be placed **without folder structure** (just, as is, including `views` folder), which is contrary to extensions for example, which can be placed in subfolders, etc. That would help a lot to newbies, like me.

Aside above, thank you very much for a wonderful extension, which saves hours of coding!

**Comment by schmunk42** [comment]
Thanks for your feedback, I'll review it - PRs are also always highly welcome.
Did you manually install the extension - not via composer?

**Comment by trejder** [comment]
I didn't make a PR, because I don't knop, which version you prefer -- `edatabase` or `database` -- and therefore, whether my PR should fix documentation or code?

Yes, manually. I don't know and I don't use composer. Later, I have manually altered my local version to have `DatabaseCommand` and use `yiic database`.

**Comment by schmunk42** [comment]
I created another issue for the broken action.

What's about moving [this section](https://github.com/schmunk42/database-command#configuration) more up and add the custom path info there, eg "replace vendor.schmunk42 ...."?
With the config setting you can run it with `yiic database` also.

**Comment by trejder** [comment]
You're absolutely right. This section is way to far. So far, that I didn't even read it. With this information on top (actually, merged into "Installation" section IMHO) everything can be solved nice and easily.
